### ISSUE TITLE
身為一個Nydia 我覺得卡片的陰影太重了 希望可以調整

### ISSUE THREAD

**Issue by nydia00000** [jh6120v/scrum-poker#12]

**Comment by nydia00000** [comment]
![image](https://user-images.githubusercontent.com/39792530/65932866-eb1c0500-e441-11e9-94da-ca5f25c49f3e.png)

**Comment by jh6120v** [comment]
感謝您寶貴的意見，Scrum Poker 將會在 0.0.3 版做此更新！
