### ISSUE TITLE
點卡片之外 藍色的地方可以返回首頁

### ISSUE THREAD

**Issue by nydia00000** [jh6120v/scrum-poker#13]
![image](https://user-images.githubusercontent.com/39792530/65932914-1dc5fd80-e442-11e9-8582-4d4e3c289b30.png)

**Comment by yschen25** [comment]
認同+1

**Comment by jh6120v** [comment]
感謝您寶貴的意見，Scrum Poker 將會在 0.0.3 版做此更新！
