### ISSUE TITLE
為了維持設計風格一致，文字應該都不可以有陰影，要不然真的眼睛痛QQQQQQ

### ISSUE THREAD

**Issue by nydia00000** [jh6120v/scrum-poker#38]

**Comment by nydia00000** [comment]
![image](https://user-images.githubusercontent.com/39792530/66176767-8d7df780-e691-11e9-82a8-48980e07dc9f.png)

**Comment by jh6120v** [comment]
https://github.com/jh6120v/scrum-poker/pull/42
