### ISSUE TITLE
其實可以把Back 前面的 "<" 刪掉 因為他很醜

### ISSUE THREAD

**Issue by nydia00000** [jh6120v/scrum-poker#39]

**Comment by nydia00000** [comment]
或者換成半形的 "<"

![image](https://user-images.githubusercontent.com/39792530/66176752-835bf900-e691-11e9-8fdb-2329e9ce140f.png)

**Comment by jh6120v** [comment]
https://github.com/jh6120v/scrum-poker/pull/42
