### ISSUE TITLE
For Testing Purposes Only 字體大一點 & 位置上去一點 

### ISSUE THREAD

**Issue by nydia00000** [jh6120v/scrum-poker#41]
font size: 18
文字上移大約 10-20 px
要不然XR 會很靠近下面的線 看起來醜醜ㄉ

**Comment by jh6120v** [comment]
由於手機款式眾多，不想做過多的判斷，所以會試著調整成通用格式。

**Comment by jh6120v** [comment]
https://github.com/jh6120v/scrum-poker/pull/42
